

export const authConstant = {
    SIGNUP_REQUEST : 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
}

export const postConstant = {
    ADD_POST_REQUEST : 'ADD_POST_REQUEST',
    ADD_POST_SUCCESS : 'ADD_POST_SUCCESS',
    ADD_POST_FAILURE : 'ADD_POST_FAILURE',
    GET_POST_REQUEST : 'GET_POST_REQUEST',
    GET_POST_SUCCESS : 'GET_POST_SUCCESS',
    GET_POST_FAILURE : 'GET_POST_FAILURE',
    ADD_COMMENT_REQUEST : 'ADD_COMMENT_REQUEST',
    ADD_COMMENT_SUCCESS : 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILURE : 'ADD_COMMENT_FAILURE',
    GET_SINGLE_POST_REQUEST : 'GET_SINGLE_POST_REQUEST',
    GET_SINGLE_POST_SUCCESS : 'GET_SINGLE_POST_SUCCESS',
    GET_SINGLE_POST_FAILURE : 'GET_SINGLE_POST_FAILURE'
}
